config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, except: [:new, :create] do
    get '/profile', to: 'profiles#show'
    get '/profile/edit', to: 'profiles#edit'
    put '/profile', to: 'profiles#update'
    get '/friends', to: 'friendships#index'
  end

  resources :posts do
    resources :comments, only: [:create]
  end
  resources :friendships, only: [:create, :update, :destroy]
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
end

app/controllers/profiles_controller.rb
# User's profile
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_owner, only: [:edit, :update]

  def show
    load_user
    build_post
    load_profile
    load_posts
    unless owner?(@user)
      @posts = [] unless they_are_friends?(@user)
    end
  end

  def edit
    load_user
    load_profile
  end

  def update
    load_user
    load_profile
    insert_attributes_to_profile

    if @profile.save
      redirect_to user_profile_path(@user)
    else
      render :edit
    end
  end

  private

  def insert_attributes_to_profile
    @profile.attributes = profile_params
  end

  def profile_params
    params.fetch(:profile, {}).permit(:gender,
                                      :status,
                                      :quote,
                                      :birthdate,
                                      :work,
                                      :education,
                                      :description,
                                      :live,
                                      :hometown,
                                      :nickname,
                                      :avatar)
  end

  def load_user
    @user ||= User.find(params[:user_id])
  end

  def load_profile
    @profile = @user.profile
  end

  def build_post
    @post = @user.posts.build
  end

  def load_posts
    @posts = @user.posts.all
  end

  def verify_owner
    load_user
    redirect_to root_url unless owner?(@user)
  end

  def they_are_friends?(user)
    current_user.friends?(user) || current_user.inverse_friends?(user)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def relationship_options
    [['Single'],
     ['In a Relationship'],
     ['Complicated'],
     ['Married'],
     ['Divorced']]
  end

  def friendship_status_button
    if current_user.friends?(@user) || current_user.inverse_friends?(@user)
      'unfriend'
    elsif current_user.request_from?(@user)
      'accept_request'
    elsif current_user.already_requested?(@user)
      'cancel_request'
    else
      'friend_request'
    end
  end
end

app/views/profiles/_image_card.html.erb
<div class="row">
  <div class="col s12 m12">
    <div class="card">
      <div class="card-image">
        <%= image_tag @profile.avatar.url %>
        <span class="card-title"><%= @user.full_name %></span>
      </div>
      <div class="card-content">
        <p><%= @profile.description %></p>
      </div>
      <% if @user == current_user %>
      <div class="card-action">
        <%= link_to "Edit Profile", user_profile_edit_path(@user) %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/_user_info.html.erb
<ul>
  <li>Nickname: <%= @profile.nickname %></li>
  <li>Work: <%= @profile.work %></li>
  <li>Education: <%= @profile.education %></li>
  <li>Status: <%= @profile.status %></li>
  <li>Gender: <%= @profile.gender %></li>
  <li>Live in: <%= @profile.live %></li>
  <li>Hometown: <%= @profile.hometown %></li>
  <li>Birthdate: <%= @profile.birthdate %></li>
  <li>Quote: <%= @profile.quote %></li>
</ul>

app/views/profiles/edit.html.erb
<script type="text/javascript">
      $(document).ready(function(){
        $('select').material_select();
        $('.datepicker').pickadate({
          selectMonths: true, // Creates a dropdown to control month
          selectYears:  100, // Creates a dropdown of years to control year
          max: true
        });
      });
</script>

<div class="row">
  <div class="col s12">
    <center class="profile-form">
    <h5>Edit Profile</h5>
    <div class="row">
      <%= form_for @profile, url: user_profile_path(@user), method: :put, html: { multipart: true } do |f| %>

        <div class="file-field input-field">
          <div class="btn">
            <span>File</span>
            <%= f.file_field :avatar %>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
           <%= f.label :nickname %>
           <%= f.text_field :nickname %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons prefix">mode_edit</i>
            <%= f.label :description, id: 'icon_prefix2' %>
            <%= f.text_area :description, id: 'icon_prefix2', class: 'materialize-textarea' %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.label :work %>
            <%= f.text_field :work %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.label :education %>
            <%= f.text_field :education %>
          </div>
        </div>

       
        <div class="row">
           <%= f.label :status %>
          <div class="input-field col s12">
            <%= f.select :status, options_for_select(relationship_options) %>
          </div>
        </div>

        <div class="row">
          <%= f.label :gender %>
          <div class="input-field col s12">
            <%= f.select :gender, options_for_select(['Male', 'Female'])  %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
           <%= f.label :live %>
            <%= f.text_field :live %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
           <%= f.label :hometown %>
            <%= f.text_field :hometown %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
           <%= f.label :birthdate %>
           <%= f.date_field :birthdate, class: "datepicker" %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
           <%= f.label :quote %>
            <%= f.text_field :quote %>
          </div>
        </div>

        <div class="row">
          <div class="waves-effect waves-light btn">
           <%= f.submit "Update Profile" %>
          </div>
           <%= link_to "Cancel", root_url, class: 'waves-effect waves-light btn' %>
        </div>
        

      <% end %>
    </div>
    </center>
  </div>
</div>    

app/views/profiles/show.html.erb
<!-- User Profile -->
<div class="row">  
  <div class="col s4" id="info-col">
    <%= render 'image_card' %>
    <% unless owner?(@user) %>
    <%= render "users/#{friendship_status_button}" %> 
    <% end %>         
    <%= render 'user_info' %>
    <%= link_to 'show all friends', user_friends_path(@user.id) %> 
  </div>
  <div class='col s8'>
    <div class="section">
      <%= render 'shared/post_form' if owner?(@user) %>
    </div>
    <div class="divider"></div>
    <div class="section">
      <%= render 'shared/users_posts' %>
    </div>
  </div>
</div>