config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, except: [:new, :create] do
    get '/profile', to: 'profiles#show'
    get '/profile/edit', to: 'profiles#edit'
    put '/profile', to: 'profiles#update'
    get '/friends', to: 'friendships#index'
  end

  resources :posts do
    resources :comments, only: [:create]
  end
  resources :friendships, only: [:create, :update, :destroy]
end

app/views/shared/_comment_form.html.erb
<%= form_for @comment, url: post_comments_path(params[:id])  do |f| %>

  <%= f.text_field :reply, placeholder: 'comment...' %>

  <%= f.submit 'Comment' %>
<% end %>

app/views/shared/_post_form.html.erb
<div class="post-form">
  <%= form_for @post do |f| %>
    
    <%= f.text_area :content, placeholder: 'Say some...', class: 'post-content' %> 

    <%= f.submit 'Post' %>  

  <% end %>
</div>

app/views/shared/_users_posts.html.erb
<ul class="collection">
  <% if @posts.any? %>
    <% @posts.each do |post| %>
      <li class="collection-item avatar">
<!-- All Posts -->
        <%= image_tag(post.user.profile.avatar.url, class: 'circle') %>
        <span class="title" id="title-post"><%= link_to post.user.full_name, post.user %></span>
        <p><%= post.content %></p>

        <%= link_to content_tag(:i, 'comment', class: 'tiny material-icons'), post_path(post) %>
<!-- Comments Count Per Post -->
        <% if post.comments.any? %>
          <%= post.comments.count %>
        <% end %>
        <div>
          Posted: <%= time_ago_in_words(post.created_at) %> ago
        </div>
      </li>
    <% end %>
  <% end %>
</ul>