config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, except: [:new, :create] do
    get '/profile', to: 'profiles#show'
    get '/profile/edit', to: 'profiles#edit'
    put '/profile', to: 'profiles#update'
    get '/friends', to: 'friendships#index'
  end

  resources :posts do
    resources :comments, only: [:create]
  end
  resources :friendships, only: [:create, :update, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="footer-copyright">
    <div class="container">
    © 2016 RobOdin-Book created by: <a class="grey-text text-lighten-4" href="https://github.com/RobPando">Roberto Pando</a>
    <a class="grey-text text-lighten-4 right" href="http://www.theodinproject.com">For: The Odin Project</a>
    </div>
  </div>
</footer>
            

app/views/layouts/_login_nav.html.erb
                          <!-- NOT Signed in nav bar -->
<ul class="right hide-on-med-and-down">
  <% unless user_signed_in? %>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>

    <li><i class="material-icons prefix">account_circle</i></li>
    <li>
      <%= f.email_field :email, autofocus: true, placeholder: 'Email', class: 'input-field col s6' %>
    </li>

    <li><i class="material-icons prefix">vpn_key</i></li>
    <li><%= f.password_field :password, autocomplete: "off", class: 'input-field col s6' %></li>

    <li>
      <% if devise_mapping.rememberable? -%>
        <%= f.check_box :remember_me, class: 'field' %>
        <%= f.label :remember_me %>
      <% end -%>        
    </li>

    <li class="btn waves-effect waves-light"><%= f.submit "Log in", class: 'action' %></li>
    
    <% end %>
  <% else %>
                        <!-- Signed in nav bar -->
    <li>
       <%= form_tag '/users', method: :get do %>
        <div class="input-field">
          <%= search_field_tag :search %>
          <%= label_tag :search, content_tag(:i, 'search', class: 'material-icons') %>
          <i class="material-icons">close</i>
        </div>
      <% end %>
    </li>

    <li><%= link_to "Profile", user_profile_path(current_user) %></li>
    <li><%= link_to "Home", posts_path %></li>
    <li><a class="dropdown-button" href="#!" data-activates="dropdown2"><i class="material-icons right">supervisor_account</i>Notifications</a></li>
    <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><i class="material-icons right">arrow_drop_down</i></a></li>
  </ul>
<% end %>

app/views/layouts/_nav.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
  <li class="divider"></li>
  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
</ul>

<% if user_signed_in? %>
<ul id="dropdown2" class="dropdown-content">
  <% if load_friend_requests.any? %>
    <li>Requests</li>
    <li class="divider"></li>
    <% load_friend_requests.each do |request| %>
      <li>
        <%= link_to request.user.full_name, user_profile_path(request.user) %>
        <p>
          <%= link_to 'Accept', friendship_path(request), method: :put, class: 'accept-btn'%>
          <%= link_to 'Ignore', friendship_path(request), method: :delete, class: 'ignore-btn' %>
        </p>
      </li>
      <li class="divider"></li>
    <% end %>
  <% else %>
    <li><%= link_to 'No requests', '#' %></li>
    <li class="divider"></li>
  <% end %>
</ul>
<% end %>
<nav>
  <div class="nav-wrapper">
    <%= link_to " Odin-Book", root_url, class: "brand-logo" %>

    <% unless devise_controller? %>
      <%= render 'layouts/login_nav' %>
    <% else %>
      <% unless user_signed_in? %>
      <ul class="right hide-on-med-and-down">
        <li class="waves-effect waves-light btn"><%= link_to "Sign Up", root_url %></li>
      </ul>
      <% end %>
    <% end %>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/nav' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
  
</html>